# Generated by Django 3.1.8 on 2021-04-14 11:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('hostname', models.CharField(blank=True, max_length=2000, null=True, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=10)),
                ('verify', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['hostname'],
            },
        ),
    ]
